from numba import njit
import numpy as np
import glm
import math

WINDOW_RESOLUTION = glm.vec2(1360, 768)
BACKGROUND_COLOR = glm.vec4(0.1, 0.1, 0.1, 1.0)

ASPECT_RATIO = WINDOW_RESOLUTION.x / WINDOW_RESOLUTION.y
FOV_DEG = 50
VERTICAL_FOV = glm.radians(FOV_DEG)
HORIZONTAL_FOV = 2 * math.atan(math.tan(VERTICAL_FOV / 2) * ASPECT_RATIO)
NEAR = 0.1
FAR = 2000.0
PITCH_MAX = glm.radians(89.0)

PLAYER_SPEED = 0.005
PLAYER_SENSITIVITY = 0.002
PLAYER_ROTATION_SPEED = 0.003
PLAYER_POSITION = glm.vec3(0, 0, 1)